using UnityEngine;
using UnityEngine.InputSystem;

public class HeroInputController : MonoBehaviour, IInputSystem
{
    private InputActions _inputActions;
    private bool _moveForward = false;
    private bool _moveBack = false;
    private bool _jump = false;
    private bool _seatDown = false;
    private bool _block = false;
    private bool _attack = false;
    private bool _superAttack1 = false;
    private bool _superAttack2 = false;

    private void Awake()
    {
        _inputActions = new InputActions();
    }

    private void OnEnable()
    {
        _inputActions.hero.Enable();

        _inputActions.hero.MoveForward.performed += OnMoveForward;
        _inputActions.hero.MoveForward.canceled += OnMoveForward혀nceled;
        _inputActions.hero.MoveBack.performed += OnMoveBack;
        _inputActions.hero.MoveBack.canceled += OnMoveBack혀nceled;
        _inputActions.hero.Jump.performed += OnJump;
        _inputActions.hero.Jump.canceled += OnJump혀nceled;
        _inputActions.hero.SeatDown.performed += OnSeatDown;
        _inputActions.hero.SeatDown.canceled += OnSeatDown혀nceled;

        _inputActions.hero.Block.performed += OnBlock;
        _inputActions.hero.Block.canceled += OnBlock혀nceled;
        _inputActions.hero.Attack.performed += OnAttack;
        _inputActions.hero.Attack.canceled += OnAttack혀nceled;
        _inputActions.hero.SuperAttack1.performed += OnSuperAttack1;
        _inputActions.hero.SuperAttack1.canceled += OnSuperAttack1혀nceled;
        _inputActions.hero.SuperAttack2.performed += OnSuperAttack2;
        _inputActions.hero.SuperAttack2.canceled += OnSuperAttack2혀nceled;
    }

    private void OnDisable()
    {
        _inputActions.hero.MoveForward.performed -= OnMoveForward;
        _inputActions.hero.MoveForward.canceled -= OnMoveForward혀nceled;
        _inputActions.hero.MoveBack.performed -= OnMoveBack;
        _inputActions.hero.MoveBack.canceled -= OnMoveBack혀nceled;
        _inputActions.hero.Jump.performed -= OnJump;
        _inputActions.hero.Jump.canceled -= OnJump혀nceled;
        _inputActions.hero.SeatDown.performed -= OnSeatDown;
        _inputActions.hero.SeatDown.canceled -= OnSeatDown혀nceled;

        _inputActions.hero.Block.performed -= OnBlock;
        _inputActions.hero.Block.canceled -= OnBlock혀nceled;
        _inputActions.hero.Attack.performed -= OnAttack;
        _inputActions.hero.Attack.canceled -= OnAttack혀nceled;
        _inputActions.hero.SuperAttack1.performed -= OnSuperAttack1;
        _inputActions.hero.SuperAttack1.canceled -= OnSuperAttack1혀nceled;
        _inputActions.hero.SuperAttack2.performed -= OnSuperAttack2;
        _inputActions.hero.SuperAttack2.canceled -= OnSuperAttack2혀nceled;


        _inputActions.hero.Disable();
    }

    private void OnMoveForward(InputAction.CallbackContext context) { _moveForward = true; }
    private void OnMoveForward혀nceled(InputAction.CallbackContext context) { _moveForward = false; }
    private void OnMoveBack(InputAction.CallbackContext context) { _moveBack = true; }
    private void OnMoveBack혀nceled(InputAction.CallbackContext context) { _moveBack = false; }
    private void OnSeatDown(InputAction.CallbackContext context) { _seatDown = true; }
    private void OnSeatDown혀nceled(InputAction.CallbackContext context) { _seatDown = false; }
    private void OnJump(InputAction.CallbackContext context) { _jump = true; }
    private void OnJump혀nceled(InputAction.CallbackContext context) { _jump = false; }
    private void OnBlock(InputAction.CallbackContext context) { _block = true; }
    private void OnBlock혀nceled(InputAction.CallbackContext context) { _block = false; }
    private void OnAttack(InputAction.CallbackContext context) { _attack = true; }
    private void OnAttack혀nceled(InputAction.CallbackContext context) { _attack = false; }
    private void OnSuperAttack1(InputAction.CallbackContext context) { _superAttack1 = true; }
    private void OnSuperAttack1혀nceled(InputAction.CallbackContext context) { _superAttack1 = false; }
    private void OnSuperAttack2(InputAction.CallbackContext context) { _superAttack2 = true; }
    private void OnSuperAttack2혀nceled(InputAction.CallbackContext context) { _superAttack2 = false; }

    public InputFlags GetInputValues()
    {
        return new InputFlags
        {
            MoveForward = _moveForward,
            MoveBack = _moveBack,
            Jump = _jump,
            SeatDown = _seatDown,
            Block = _block,
            Attack = _attack,
            SuperAttack1 = _superAttack1,
            SuperAttack2 = _superAttack2,
        };
    }
}
